name: 'Setup Cish'
description: 'Setup cish'
inputs:
  version:
    description: 'Version of cish'
    required: true
    default: 'v0.3.2'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
