name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: ./build.sh

      - name: docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker/build/
          file: ./docker/build/Dockerfile
          tags: alexanderlindner/cish:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  main-cish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: ${{ !env.ACT }}
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Checkout
        uses: actions/checkout@v2

      - name: setup cish
        uses: ./.github/actions

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-



      - name: build
        run: ./build.cish

      - name: docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./docker/build/
          file: ./docker/build/Dockerfile
          tags: alexanderlindner/cish:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
