name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Checkout
        uses: actions/checkout@v2

      - name: build cish
        run: ./build.sh

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker/build
          file: ./Dockerfile
          tags: alexanderlindner/cish:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
