name: documentation

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docs
        run: |
          if [[ "$GITHUB_REF" = refs/heads/* ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/heads/};
          elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
          export VERSIONING_GIT_TAG=${GITHUB_REF#refs/tags/};
          elif [[ "$GITHUB_REF" = refs/pull/*/merge ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/};
          VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH%/merge};
          fi
          ./mvnw clean package javadoc:javadoc

      - name: Deploy doc "compiler"
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: ./compiler/target/site/apidocs/
          target-folder: ./docs/compiler/
          CLEAN: true

      - name: Deploy doc "interpreter"
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: ./interpreter/target/site/apidocs/
          target-folder: ./docs/interpreter/
          CLEAN: true

      - name: Deploy doc "lang"
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: ./lang/target/site/apidocs/
          target-folder: ./docs/lang/
          CLEAN: true

      - name: Deploy doc "extension"
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          folder: ./extension/target/site/apidocs/
          target-folder: ./docs/extension/
          CLEAN: true