name: documentation

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build docs
        run: |
          if [[ "$GITHUB_REF" = refs/heads/* ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/heads/};
          elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
          export VERSIONING_GIT_TAG=${GITHUB_REF#refs/tags/};
          elif [[ "$GITHUB_REF" = refs/pull/*/merge ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/};
          VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH%/merge};
          fi
          ./mvnw -DskipTests -Dversioning.disable=true -B clean package install javadoc:javadoc javadoc:aggregate

      - name: Deploy doc 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          #          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./target/site/apidocs/
          target-folder: ./docs/
          clean: true