---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          if [[ "$GITHUB_REF" = refs/heads/* ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/heads/};
          elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
          export VERSIONING_GIT_TAG=${GITHUB_REF#refs/tags/};
          elif [[ "$GITHUB_REF" = refs/pull/*/merge ]]; then
          export VERSIONING_GIT_BRANCH=${GITHUB_REF#refs/};
          VERSIONING_GIT_BRANCH=${VERSIONING_GIT_BRANCH%/merge};
          fi
          ./build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar
            target/cish

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}